# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

minimum_pre_commit_version: 2.20.0
fail_fast: false
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        exclude: resources/update-trigger.mov
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: no-commit-to-branch
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      # - id: forbid-binary
      - id: git-check
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.18.3
    hooks:
      - id: check-jsonschema
        name: Validate GitHub Workflows
        files: ^\.github/workflows/.*\.yml
        types:
          - yaml
        args:
          - --schemafile
          - https://json.schemastore.org/github-workflow.json
      - id: check-jsonschema
        name: Validate GitHub Actions
        files: >
          (?x)^(
            .*/action\.(yml|yaml)|
            \.github/actions/.*
          )$
        types:
          - yaml
        args:
          - --schemafile
          - https://json.schemastore.org/github-action
      - id: check-jsonschema
        name: Validate DependaBot
        files: ^\.github/dependabot\.yml
        types:
          - yaml
        args:
          - --schemafile
          - https://json.schemastore.org/dependabot-2.0.json
      - id: check-jsonschema
        name: Validate Pre-commit
        files: .*\.pre-commit-config\.yaml
        types:
          - yaml
        args:
          - --schemafile
          - https://json.schemastore.org/pre-commit-config.json
      - id: check-jsonschema
        name: Validate Renovate
        files: ^\.github/renovate\.json
        types:
          - json
        args:
          - --schemafile
          - https://docs.renovatebot.com/renovate-schema.json
          - --disable-format
